# Generated by Django 4.0.4 on 2022-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vareaze_id',
            field=models.CharField(blank=True, default='FCTGDW1KJYGT', editable=False, max_length=10, unique=True),
        ),
    ]
