# Generated by Django 4.0.4 on 2022-06-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_vareaze_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vareaze_id',
            field=models.CharField(blank=True, default='PXAR4E7JHVPN', editable=False, max_length=10, unique=True),
        ),
    ]
