# Generated by Django 4.0.4 on 2022-06-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_vareaze_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vareaze_id',
            field=models.CharField(blank=True, default='GYUSFL0IY2IO', editable=False, max_length=10, unique=True),
        ),
    ]
