# Generated by Django 4.0.4 on 2022-06-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_vareaze_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vareaze_id',
            field=models.CharField(blank=True, default='MCLR5RVP3OU1', editable=False, max_length=10, unique=True),
        ),
    ]
