# Generated by Django 4.0.4 on 2022-06-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_vareaze_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='vareaze_id',
            field=models.CharField(blank=True, default='93U47RB8DZNM', editable=False, max_length=10, unique=True),
        ),
    ]
