# Generated by Django 4.0.4 on 2022-06-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('vareaze_id', models.CharField(max_length=12)),
                ('sent_to', models.CharField(max_length=20)),
            ],
        ),
    ]
