# Generated by Django 4.0.4 on 2022-06-04 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vareaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
