# Generated by Django 4.0.4 on 2022-06-04 21:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vareaze', '0003_alter_contract_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 21, 45, 43, 543453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sent_to',
            field=models.CharField(max_length=12),
        ),
    ]
