# Generated by Django 4.0.4 on 2022-06-04 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vareaze', '0004_remove_contract_expiration_date_contract_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 22, 16, 2, 956707, tzinfo=utc)),
        ),
    ]
