# Generated by Django 4.0.4 on 2022-06-05 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vareaze', '0009_alter_contract_date_added_alter_contract_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='text',
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 0, 40, 36, 651347, tzinfo=utc)),
        ),
    ]
